source 'https://github.com/CocoaPods/Specs.git'
source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'
source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecsMirror.git'
 
    
abstract_target '' do
    
	pod 'JRSwizzle', '~> 1.0'

    target 'Swizzling'
        
end


